### ISSUE TITLE
Project License

### ISSUE THREAD

**Issue by gregorfes** [mipen/ModLib#1]
Hi, @mipen!
I was wondering what license does this library use? I and probably others modders won't be able to use it if you won't specify a license. I would recommend MIT or a MIT compatible one!

**Comment by mipen** [comment]
Thanks for reminding me! I've chosen the the GNU GPL v3 licence for the project, which is similar to MIT except it can't be redistrubuted without the same or a similarly permissible licence.

**Comment by Aberro** [comment]
Too bad. I can't agree to use GPL.

**Comment by mipen** [comment]
@Aberro The licence has been changed to MIT now as it doesn't cause any issues

**Comment by Aberro** [comment]
That's nice! And unexpected..
