### ISSUE TITLE
MBOptionScreen workaround

### ISSUE THREAD

**Issue by brandonm4** [mipen/ModLib#20]
Since MBOptionScreen is messing with ModLib saving, during the pre-check to see if ModLib is loaded, I'm also checking to see if MBOptionScreen is loaded.  If so, I basically re-initialize the menu and add a ModLib Settings entry.  This seems to bypass the MBOptionScreen injection and let's the ModLib modules start saving their settings again.

This is just a work-around.  Ideally, MBOptionScreen would play nicer with ModLib since it's injecting into it.
https://github.com/brandonm4/BannerlordMods/blob/master/TournamentsXPanded.Settings/SettingsHelperModLib.cs

The other downside is I had to re-implement ModOptionsGauntletScreen since it's internal to ModLib.

Very open to alternate suggestions.

**Comment by Aragas** [comment]
MBOptionScreen's behaviour was quite aggressive and was in bad taste.
It will be changed in the next version, adding an option to keep ModLib option screen menu intact.
MBOptionScreen will also use ModLib's saving/loading logic, so the setting will remain available for ModLib if the user decides to remove MBOptionScreen.

**Comment by Aragas** [comment]
This should be fixed with 1.1.9.
MBOptionScreen won't interfere anymore with ModLib code. It still replaces it's menu by default, but it can be changed in the settings.

**Comment by brandonm4** [comment]
I commented on Aragas's repo as well - but I have had a user upgrade to MBOptionScreen 1.1.14 and it fixed the incompatibility issues with Modlib.  So I think this issue is resolved.  (It seemed so when I was testing, but this is a nice independent confirmation)
