### ISSUE TITLE
SettingsDatabase in latest release has no public method to register SettingsBase

### ISSUE THREAD

**Issue by hunharibo** [mipen/ModLib#34]
Hi, downloaded latest binary today. Tried to follow Wiki, but its outdated. 
Since the heavy refactoring of Definitions, latest SettingsDatabase class has no public methods to register new settingsbase.

I am not experienced enough to try to fix this, so not submitting a PR, but can you take a look at it pls? Huge thanks!

**Comment by mipen** [comment]
Hi there,
You no longer need to register your settings class with the SettingsDatabase.
The changes are detailed here: https://github.com/mipen/ModLib/wiki/What's-new-in-1.3%3F
ModLib automatically detects the settings classes for all mods and adds them to the menu. If you need to access the settings when the game is starting up, do so in the OnBeforeInitialModuleScreenSetAsRoot() method of your submodule.

When I can get the courage I'll update the wiki, but for now let me know if there is anything else you need help with!

**Comment by hunharibo** [comment]
So I just base my settings class on settingsbase and it gets collected? Meaning read from disk with filedatabase and registered in settingsdatabase? Awesomesauce! Thanks!

**Comment by mipen** [comment]
Exactly :)
