### ISSUE TITLE
Support of Multiple Mods?

### ISSUE THREAD

**Issue by RalfKeller** [mipen/ModLib#9]
Hello, I have the following problem: I want my mod to be displayed in the mod option menu. If I start the mod without BannerlordTweaks it works just fine, but if I start the game with my mod AND Bannerlord Tweaks, there is a error Message saying, that there was an error loading files for zzBannerlordTweaks. "Unable to find type BannerlordTweaks.Settings, BannerlordTweaks"

StackTrace:
at ModLib.FileDatabase.LoadAllFiles(...)
...

Am I doing something wrong?

**Comment by RalfKeller** [comment]
Probably adressed in #6

**Comment by Splintertx** [comment]
Multiple modules definitely works, but it requires a lot of things to be in place. Each mod must have Harmony and ModLib dlls, your `Settings.Initialise()` and `SettingsDatabase.RegisterSettings()` calls must send correct values, your Settings class must be public, your Instance getter should create a settings file if it cannot find one (clone BannerlordTweaks.Settings design).

**Comment by mipen** [comment]
This mod is not finished yet and shouldn't be used until it is released properly. When it is released, it will be a mod of its own and you will simply add a dependancy inside your SubModule.xml file. I am in the process of writing the wiki for it and tweaking the API to be as easy to use as possible.
ModLib.dll should not be present inside your module's folder.
The mod should be released within the next 24 hours after this comment was posted.
